### ISSUE TITLE
Add Docker Compose

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#100]
Add a Docker Compose config, to make it trivial to develop locally whilst keeping distribution and `node_modules` inside a Linux container.

Trivial example:

**Dockerfile**

```
FROM node:8.6.0

WORKDIR /app
ADD package*.json ./
RUN npm i
ADD . .

EXPOSE 8000 8081

CMD npm start
```

**docker-compose.yml**

```
version: '3.3'
services:
  reactql-dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      HOST: "0.0.0.0"
      BROWSER_HOST: "0.0.0.0"
```

Related to #98 (optimising the Docker image) and #99 (enabling CORS with hot browser reloading)
